jobs:
- job: HyperionBuild
  pool:
    vmImage: ubuntu-16.04

  strategy:
    matrix:
      node_12_x:
        node_version: 12.x
      node_11_x:
        node_version: 11.x
      node_10_x:
        node_version: 10.x
      node_8_x:
        node_version: 8.x
    maxParallel: 5

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: Install Node.js

  - bash: yarn install
    displayName: Install dependencies
