// This won't be used, it's overkill. But it shows you what a completely empty AND NORMALIZED annotation looks like.
// This is where we will lean on pattern matching to ensure we are safely accessing annotation fields.
import {
  AnnotationNormalized,
  AnnotationPageNormalized,
  CanvasNormalized,
  CollectionNormalized,
  ManifestNormalized,
  RangeNormalized,
  ServiceNormalized,
} from '@hyperion-framework/types';

export const emptyAnnotation: AnnotationNormalized = {
  id: 'https://hyperion/annotation',
  type: 'Annotation',
  behavior: [],
  label: null,
  thumbnail: [],
  summary: null,
  requiredStatement: null,
  metadata: [],
  seeAlso: [],
  homepage: null,
  logo: [],
  rendering: [],
  service: [],
  accessibility: [],
  audience: [],
  body: [],
  bodyValue: null,
  canonical: null,
  created: null,
  creator: [],
  generated: null,
  generator: [],
  modified: null,
  motivation: [],
  rights: [],
  stylesheet: null,
  target: [],
  timeMode: undefined, // @todo bug? should be null.
  via: [],
  partOf: [],
};

export const emptyAnnotationPage: AnnotationPageNormalized = {
  id: 'https://hyperion/annotation-page',
  type: 'AnnotationPage',
  behavior: [],
  motivation: null,
  label: null,
  thumbnail: [],
  summary: null,
  requiredStatement: null,
  metadata: [],
  rights: null,
  items: [],
  seeAlso: [],
  homepage: null,
  logo: [],
  rendering: [],
  service: [],
};

export const emptyCanvas: CanvasNormalized = {
  id: 'https://hyperion/empty-canvas',
  type: 'Canvas',
  label: null,
  behavior: [],
  motivation: null,
  thumbnail: [],
  posterCanvas: null,
  summary: null,
  requiredStatement: null,
  metadata: [],
  rights: null,
  navDate: null,
  items: [],
  annotations: [],
  seeAlso: [],
  homepage: null,
  logo: [],
  partOf: [],
  rendering: [],
  service: [],
  duration: 0,
  height: 0,
  width: 0,
};

export const emptyCollection: CollectionNormalized = {
  id: 'https://hyperion/empty-collection',
  type: 'Collection',
  label: null,
  viewingDirection: 'left-to-right',
  behavior: [],
  motivation: null,
  thumbnail: [],
  posterCanvas: null,
  summary: null,
  requiredStatement: null,
  metadata: [],
  rights: null,
  navDate: null,
  items: [],
  annotations: [],
  seeAlso: [],
  homepage: null,
  logo: [],
  partOf: [],
  rendering: [],
  service: [],
};

export const emptyManifest: ManifestNormalized = {
  id: 'https://hyperion/empty-manifest',
  type: 'Manifest',
  annotations: [],
  behavior: [],
  homepage: null,
  items: [],
  label: null,
  logo: [],
  metadata: [],
  motivation: null,
  navDate: null,
  partOf: [],
  posterCanvas: null,
  rendering: [],
  requiredStatement: null,
  rights: null,
  seeAlso: [],
  service: [],
  start: null,
  structures: [],
  summary: null,
  thumbnail: [],
  viewingDirection: 'left-to-right',
};

export const emptyRange: RangeNormalized = {
  id: 'https://hyperion/empty-canvas',
  type: 'Range',
  label: null,
  behavior: [],
  motivation: null,
  thumbnail: [],
  posterCanvas: null,
  summary: null,
  requiredStatement: null,
  metadata: [],
  rights: null,
  navDate: null,
  items: [],
  annotations: [],
  seeAlso: [],
  homepage: null,
  logo: [],
  partOf: [],
  rendering: [],
  service: [],
  start: null,
  supplementary: null,
  viewingDirection: 'left-to-right',
};

export const emptyService: ServiceNormalized = {
  id: 'https://hyperion/empty-service',
  height: null,
  profile: [],
  protocol: '',
  sizes: [],
  tiles: [],
  width: null,
};
