/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  docs: [
    {
      type: 'doc',
      label: 'API Documentation',
      id: 'api/api',
    },
    {
      type: 'doc',
      label: 'Simple viewer',
      id: 'api/simple-viewer-context',
    },
    {
      type: 'category',
      link: { type: 'doc', id: 'api/resource-hooks/resource-hooks' },
      label: 'Resource hooks',
      items: [{ type: 'autogenerated', dirName: 'api/resource-hooks' }],
    },
    {
      type: 'category',
      link: { type: 'doc', id: 'api/hooks/hooks' },
      label: 'Hooks',
      items: [{ type: 'autogenerated', dirName: 'api/hooks' }],
    },
    {
      type: 'category',
      link: { type: 'doc', id: 'api/context/context' },
      label: 'Contexts',
      items: [{ type: 'autogenerated', dirName: 'api/context' }],
    },
    {
      type: 'category',
      link: { type: 'doc', id: 'api/in-development/in-development' },
      label: 'Future development',
      items: [{ type: 'autogenerated', dirName: 'api/in-development' }],
    },
  ],

  tutorial: [{ type: 'autogenerated', dirName: 'tutorial' }],
};

module.exports = sidebars;
